[platformio]
default_envs = esp32-p4-st7789-spi

[env:esp32-p4-st7789-spi]
platform = espressif32
board = esp32-p4
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps = 
    moononournation/GFX Library for Arduino
    mikalhart/TinyGPSPlus

; Build shortcuts (VS Code):
; Build: Ctrl+Alt+B
; Upload: Ctrl+Alt+U (press BOOT when "Connecting...")
; Monitor: Ctrl+Alt+M
; Clean: Ctrl+Alt+C
