[platformio]
default_envs = esp32-p4-minimal

[env:esp32-p4-minimal]
platform = espressif32
board = esp32-p4
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps = 
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
    adafruit/Adafruit MCP9808 Library
    adafruit/Adafruit AW9523
    mikal hart/TinyGPS++

; Development notes
; Build: Ctrl+Alt+B (VS Code) or pio run
; Upload: Ctrl+Alt+U (VS Code) or pio run -t upload (press BOOT button when "Connecting...")
; Monitor: Ctrl+Alt+M (VS Code) or pio device monitor
; Clean: Ctrl+Alt+C (VS Code) or pio run -t clean
